name: Spring Boot CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 11 using AdoptOpenJDK distribution
      - name: Set up JDK 21 
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'zulu'  

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Run Tests
        run: mvn test

      - name: Save JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app-jar
          path: target/*.jar
# Step 3: Set environment variables with secrets (for API key and DB password)
      - name: Set up environment variables with secrets
        run: |
          echo "MY_SECRET_KEY=${{ secrets.MY_SECRET_KEY }}" >> $GITHUB_ENV
          echo "MY_DB_PASSWORD=${{ secrets.MY_DB_PASSWORD }}" >> $GITHUB_ENV
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app-jar
          path: ./artifact

      - name: Deploy Application (Mock Deployment)
        run: echo "Deploying Spring Boot Application..."
